### ISSUE TITLE
GATK Module Load Missing In Rerun Script

### ISSUE THREAD

**Issue by DarioS** [Sydney-Informatics-Hub/Somatic-ShortV#8]
https://github.com/Sydney-Informatics-Hub/Somatic-ShortV/blob/8bcd9da640733ad4dd9c4b55f8e95c75a9694513/gatk4_getpileupsummaries_missing_run_parallel.pbs#L43-L46

There ought to be a `module load gatk/4.1.2.0` here somewhere.

**Comment by DarioS** [comment]
Same for `gatk4_calculatecontamination_run_parallel.pbs` (which is also missing any mention in the user guide).

**Comment by georgiesamaha** [comment]
Have added missing gatk modules to both scripts, thanks for pointing them out Dario. Will also update the documentation
